apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: cold-mongo-depl
spec:
  containers:
    - name: cold-mongo
      image: mongo
      volumeMounts:
      - mountPath: "/data/db"
        name: mongo-db
  volumes:
    - name: mongo-db
      persistentVolumeClaim:
        claimName: mongo-pvc    
---
apiVersion: v1
kind: Service
metadata:
  name: cold-mongo-srv
spec:
  selector:
    app: cold-mongo
  ports:
    - name: db
      protocol: TCP
      port: 27017
      targetPort: 27017
