name: deploy-manifests

on:
  push:
    branches: 
      - master
    paths:
      - 'infra/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Scaleway scw CLI
        uses: jawher/action-scw@v2.0.0-2
        env:
          SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
          SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_TOKEN }}
          SCW_ORGANIZATION_ID: ${{ secrets.SCW_ORGANIZATION_ID }}
          SCW_ZONE: fr-par-1
        with:
          args: k8s kubeconfig install 7278e482-90d6-422f-9db9-e3a5582a2f90 && kubectl apply -f infra/k8s && kubectl apply -f infra/k8s-prod
