name: deploy-igauth

on:
  push:
    branches: 
      - master
    paths:
      - 'igauth/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd igauth && docker build -t achoisy/igauth .
      - run: docker login $SCW_NAMESPACE -u nologin -p $SCW_SECRET_TOKEN
        env:
          SCW_NAMESPACE: ${{ secrets.SCW_NAMESPACE }}
          SCW_SECRET_TOKEN: ${{ secrets.SCW_SECRET_TOKEN }}
      - run: docker tag achoisy/igauth $SCW_NAMESPACE/igauth && docker push $SCW_NAMESPACE/igauth
        env:
          SCW_NAMESPACE: ${{ secrets.SCW_NAMESPACE }}
      - name: Scaleway scw CLI
        uses: jawher/action-scw@v2.0.0-2
        env:
          SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
          SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_TOKEN }}
          SCW_ORGANIZATION_ID: ${{ secrets.SCW_ORGANIZATION_ID }}
          SCW_ZONE: fr-par-1
        with:
          args: k8s kubeconfig install 7278e482-90d6-422f-9db9-e3a5582a2f90
      - run: kubectl rollout restart deployment igauth-depl
