name: test-portal

on:
  pull_request:
    paths:
      - 'portal/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd portal && npm install && npm run test:ci
