name: test-streamer

on:
  pull_request:
    paths:
      - 'streamer/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd streamer && npm install && npm run test:ci
      
