name: test-igauth

on:
  pull_request:
    paths:
      - 'igauth/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd igauth && npm install && npm run test:ci
